#server:
#  port: 8080
#
## database 연동 설정
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
#    url: jdbc:mysql://localhost:3306/db_swengineering?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
#    username: user_swengineering
#    password: 1234
#  thymeleaf:
#    cache: false
#
#  # spring data jpa 설정
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/db_SE?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: admin
    password: qlalfqjsgh1!
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-jpa: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey

